name: npm version && npm publish

on:
  workflow_dispatch:
    inputs:
      newversion:
        description: 'npm version {major,minor,patch}'
        required: true

env:
  node_version: 14
  email: 1062670898@qq.com

jobs:
  version_and_release:
    runs-on: ubuntu-latest
    environment:
      name: dev
    steps:
    - uses: actions/checkout@v2.4.0
      with:
        # fetch full history so things like auto-changelog work properly
        fetch-depth: 0
    - name: Use Node.js ${{ env.node_version }}
      uses: actions/setup-node@v2.5.0
      with:
        node-version: ${{ env.node_version }}
        # setting a registry enables the NODE_AUTH_TOKEN env variable where we can set an npm token.  REQUIRED
        registry-url: 'https://registry.npmjs.org'
    - run: npm install
    - run: npm test
    - run: git config --global user.email "${{ env.GIT_EMAIL }}"
    - run: git config --global user.name " ${{ github.actor }}"
    - run: git add . && git commit -m 'version prepare'
    - name: npm version && npm publish
      if: always()
      uses: bcomnes/npm-bump@v2.0.2
      with:
        git_email: ${{ env.GIT_EMAIL }}
        git_username: ${{ github.actor }}
        newversion: ${{ github.event.inputs.newversion }}
        github_token: ${{ secrets.GITHUB_TOKEN }} # built in actions token.  Passed tp gh-release if in use.
        npm_token: ${{ secrets.NPM_TOKEN }}  # user set secret token generated at npm